language: node_js
node_js: 
  - '12.18'
cache: npm
script: 
  - npm run test:unit
after_success: 
  - npm run build
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: $TOKEN
  app: unittodolists
  on:
    branch: master