language: node_js
node_js:
- '12.18'
cache: npm
script:
- npm run test:unit
after_success:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: lL/QtswIBt7HqkaWFYuSaibniuERCVGF3VnqB4Kdt1o+uDvFZKuoyA3bObZ7JMir1wiLAkafeG15YezZ7Ad3g4mEvTIEQld8dNeZpwG0BZaEBchW6GBQ01oyioe9pxbGWvFKcgqZtIpT0PCFm4Vmf+9IGF/P0WnUp4OiAPjss4RtQEUGDSMd9gIG3Alyr7AfpwsXZKri2ncSZw1pZkYmhGU6/fHByXAxZgmgqhzlkv0OmqH5YptUoA+S8iHsAogB7t6CKBUbG+/VZ7qaoJym4CzkgoA+tYA0zpsTUuWs8diLr38XBGXVY6nbVJhEH1kipzGjeSGpoWb/+g8Z2N7sEQm4AyAmEsM1ih1wWjkHhvuJz0G4xf592d8FQ9lOKafi6px3dJXnjgP8kTCcHEbVVQgYrhqnpwV4e6+V9G5jQzMVL9JvKTBG6TCKnRSjpnuUQAfR/ggrACYXs5JUfo7tYUyCneht8AHdg5Im//luH1SRxoVJ68LPyGEui/Q01XYI0fIZiLxa4tsxiksJHvzDpdJSiWBy/ru1ZRb7+Pa4hwHDH7SdUqo+iVM4kLq+Q4TaDY5YkX49wbjDOF76dPotmubDDMD4OKmBUAyGiG65R/gojEo/mt+urSL0MAGpYPbQzngAMoLLbZucR7yoXN/klWcMtdJvy29kKHYUdnrnUyg=
  on:
    repo: god-of-js/unit-tests-todo-list
  skip_cleanup: 'true'
