language: node_js
node_js:
- '12.18'
cache: npm
script:
- npm run test:unit
after_success:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: cKeDntZPI6aa74mG5RIpwqqJ0DT0vG4s69L5lk0iUmKV1vOYcMRjgWd/m579Mw7LU93AlZG1dHXh3owrBFtZgd99lbJ6xxOOtxOCM+AOAuVFtd2FDnNbqLGLxwc2CY1Zd9+d8YVx5XnfgA7aYlkQ70F7cSQcDBYA1WcaMmpBCd/yDTQpvUUEboMSTq7P3BBsoqLmCB+eeNIRiIXrS7d31VM9HCJEo6qvGbQ854jFdIrTKUcrlHjnvGOIYFrqGXKNpHxzSS99d4Pl/1C96NpptJ2XqngDo/Gzmf2BqQ6pNHj1RIklElq5WcD3X2qacoOlRyW/ykYVNCuLw8/vpyKuUqSOs+Dhq8+xA2CMNxKJdRApJva2dfYbqJPZ5Jg49pevCly1OL115gH5VKxQTyxdh6KEzmmHpdGUHwQAHOzmW8QDkCiEVCYwURUmQidcyVmSRB0Odi3nMJ+efi/5hImvxD+yDvN5/UResv1bXbcYVPw2SsHVyYO1u34DCgd7XnmCt5mtwmXvTBZq+3RcvtWtBJa7nHVnln5iDJFDiN/iO1bP39C9YC4UoyLf6wneTsW4SAZmeuodK8QYyWA2yH0ZdPxQb4Fu0WWspsDxnvPqG/Gi2Y3qO3og38MOGnVnyOxlmWFXiFLFbvtPVrli/HD1yKgh4KJwGOmq5cJAlxn2HLI=
  on:
    repo: god-of-js/unit-tests-todo-list
  skip_cleanup: 'true'
