language: node_js
node_js:
- '12.18'
cache: npm
script:
- npm run test:unit
after_success:
- npm run build
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: S09UsozW1kiW5m8gXUwUgY9ZtAL4MVu7YFAj4ha7l8oxYImwiUpl5leKuqcVqwt0BQvHpalQAz+dO5t5ZHgVAEbGtyaBVsbav2IcuYjOfBMKCxo2UmdO9U/fw4eMVu05IgXYzBwEncbpbCY4I86KC0AUol1OZgzSiLo36GJ07IChjf4MLaxbStXnD49uqeAAyXwOiGLqL4Sb+CUT10NGt1gClR8ZFKA++iToYhbNsQNL3uSxDVmFqP3yCWt+J0kxuYfpOdY13eATDDLv++/1480tAyk1TNORbuyFWDdMhd88/VKWriubRxvJDrSu8xAZJa2mX9a+PH4MPqUJ1rP2CRxHXr/NMAzlScAz8JBPzMsGNKbyT9rGKnDYV0TvXmfH592ObsjQXRzqciCJzW+oOSaQSAK+WOjfzv3H3w1UnwOIznqXFLouFg5cjQd3Y3zWO1KJ2tvI6TW0M8g7ifTNMFXvnSKLJTmgIj8ohxC1HNhMIu08WxkhGP+VVyE8eZw08fprlN+JkKYtk2tbv9iqimfVa2uWzx5nLOxvNvGK6TtQhm3E8w8Nt9qaKqA/HsE0jRRAvAGNlanN8kMWegp/qq3TGVoBpU1BiQaMH5RnsqWXvgKVcIzi2bmyrxIG2l1zE0o619qLB7wx2/S77TAUKRFAzi/1+UOPp3/Tx01ooqs=
  app: unittodolists
  on:
    branch: master
