orbs:
  heroku: circleci/heroku@1.2.2
version: 2.1
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
          post-steps:
            - run: npm run build
          pre-steps:
            - run: npm run test:unit