version: 2.1
orbs:
  node: circleci/node@1.1
  heroku: circleci/heroku@0.0.10
  coveralls: coveralls/coveralls@1.0.6
workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job  
          requires:
            - build
          filters:
            branches:
              only: master
jobs:
  build:
    docker:
    - image: circleci/node:11.8-browsers
    environment:
      NODE_ENV: test
    steps:
    - checkout # special step to check out source code to working directory
    - restore_cache: # special step to restore the dependency cache
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: install npm dependencies
        command: npm install
    - save_cache: # special step to save the dependency 
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
        - ./node_modules
    - run:
        name: running unit tests
        command: npm run test:unit
    - run: # run code coverage report
          name: code-coverage
          command: npm run coveralls
    - coveralls/upload  
    - run: 
        commands:
          upload:
            parameters:
              path_to_lcov:
                description: >
                  Local path to the lcov output file produced by your test suite.
                  An error will be thrown if the file can't be found. This is the file that will be sent to the Coveralls API.
                type: string
                default: ./coverage/lcov.info
              token:
                description: Your Coveralls Repo token defined in your Circle's Environment Variables.
                type: env_var_name
                default: COVERALLS_REPO_TOKEN
notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=${COVERALLS_REPO_TOKEN}