version: 2.1
orbs:
  node: circleci/node@1.1
  heroku: circleci/heroku@0.0.10
  coveralls: coveralls/coveralls@1.0.6
workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job  
          requires:
            - build
          filters:
            branches:
              only: master
jobs:
  build:
    docker:
    - image: circleci/node:11.8-browsers
    steps:
    - checkout # special step to check out source code to working directory
    - restore_cache: # special step to restore the dependency cache
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: install npm dependencies
        command: npm install
    - save_cache: # special step to save the dependency 
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
        - ./node_modules
    - run:
        name: running unit tests
        command: npm run test:unit
    - coveralls/upload