version: 2.1
orbs:
  node: circleci/node@1.1
  heroku: circleci/heroku@1.2.2
jobs:
  build:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test:unit
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
          pre-steps:
            - run: npm run build